/* eslint-disable no-inner-declarations */
import { inject, Options, sha1, validOrigin } from "@src/utils";
import injectPath from "./injectPlayer?script&module";

const videoId = window.location.pathname.split("/").slice(-1)[0];
if (videoId) {
  console.log(inject, injectPath);
  inject(injectPath);
  // // alternate:
  // function injectScript(content: () => void) {
  //   const script = document.createElement("script");
  //   script.textContent = `
  //   (${content.toString()})();
  // `;
  //   (document.head || document.documentElement).appendChild(script);
  // }

  // function modifyYouTubeConfig() {
  //   // @ts-expect-error "ytcfg" is a YT global
  //   const currentConfig = window.ytcfg.d();

  //   const saneConfigs = {
  //     H5_enable_full_pacf_logging: true,
  //     H5_use_async_logging: true,
  //     ab_det_el_h: true,
  //     ab_det_fet_wr: true,
  //     ab_det_fet_wr_en: true,
  //     ab_det_gen_re: true,
  //     ab_fk_sk_cl: true,
  //     action_companion_center_align_description: true,
  //     allow_skip_networkless: true,
  //     att_web_record_metrics: true,
  //     autoescape_tempdata_url: true,
  //     browse_next_continuations_migration_playlist: true,
  //     c3_watch_page_component: true,
  //     cache_utc_offset_minutes_in_pref_cookie: true,
  //     cancel_pending_navs: true,
  //     check_login_info_at_app_init_time: true,
  //     check_user_lact_at_prompt_shown_time_on_web: true,
  //     clear_user_partitioned_ls: true,
  //     client_respect_autoplay_switch_button_renderer: true,
  //     cold_missing_history: true,
  //     compress_gel: true,
  //     copy_login_info_to_st_cookie: true,
  //     csi_config_handling_infra: true,
  //     csi_on_gel: true,
  //     decorate_autoplay_renderer: true,
  //     defer_menus: true,
  //     defer_overlays: true,
  //     defer_rendering_outside_visible_area: true,
  //     deprecate_csi_has_info: true,
  //     deprecate_pair_servlet_enabled: true,
  //     desktop_add_to_playlist_renderer_dialog_popup: true,
  //     desktop_animate_miniplayer: true,
  //     desktop_client_release: true,
  //     desktop_delay_player_resizing: true,
  //     desktop_enable_dmpanel_click_drag_scroll: true,
  //     desktop_enable_dmpanel_scroll: true,
  //     desktop_enable_dmpanel_wheel_scroll: true,
  //     desktop_keyboard_capture_keydown_killswitch: true,
  //     desktop_mix_use_sampled_color_for_bottom_bar: true,
  //     desktop_mix_use_sampled_color_for_bottom_bar_search: true,
  //     desktop_mix_use_sampled_color_for_bottom_bar_watch_next: true,
  //     desktop_notification_high_priority_ignore_push: true,
  //     desktop_notification_set_title_bar: true,
  //     desktop_search_prominent_thumbs: true,
  //     desktop_sparkles_light_cta_button: true,
  //     desktop_swipeable_guide: true,
  //     desktop_use_new_history_manager: true,
  //     disable_banner_collapsing_when_hidden: true,
  //     disable_cached_masthead_data: true,
  //     disable_child_node_auto_formatted_strings: true,
  //     disable_dependency_injection: true,
  //     disable_enf_isd: true,
  //     disable_features_for_supex: true,
  //     disable_legacy_desktop_remote_queue: true,
  //     disable_pacf_logging_for_memory_limited_tv: true,
  //     disable_pause_on_linked_comment_nav: true,
  //     disable_safari_ui_status_check: true,
  //     disable_simple_mixed_direction_formatted_strings: true,
  //     disable_super_chat_buy_button: true,
  //     disable_thumbnail_preloading: true,
  //     embeds_transport_use_scheduler: true,
  //     embeds_web_nwl_disable_nocookie: true,
  //     empty_attributed_string_killswitch: true,
  //     enable_ab_report_on_errorscreen: true,
  //     enable_ab_rp_int: true,
  //     enable_active_view_display_ad_renderer_web_home: true,
  //     enable_ad_context_in_vss_pings: true,
  //     enable_ads_web_ep_buenos_aires_and_padding_fix: true,
  //     enable_async_ab_enf: true,
  //     enable_autotrim_enhanced_video_on_web: true,
  //     enable_browser_cookie_status_monitoring: true,
  //     enable_buenos_aires_typography: true,
  //     enable_button_behavior_reuse: true,
  //     enable_call_to_action_clarification_renderer_bottom_section_conditions:
  //       true,
  //     enable_channel_page_header_profile_section: true,
  //     enable_channel_page_modern_profile_section: true,
  //     enable_client_sli_logging: true,
  //     enable_client_streamz_web: true,
  //     enable_cloud_save_download_data_succeeded_check: true,
  //     enable_creator_details_shelf_m2: true,
  //     enable_custom_survey_impression_logging: true,
  //     enable_desktop_amsterdam_info_panels: true,
  //     enable_desktop_companion_impression_on_first_visible: true,
  //     enable_desktop_fountain_reaction_item_data_consumption: true,
  //     enable_desktop_search_bigger_thumbs: true,
  //     enable_desktop_search_bigger_thumbs_square: true,
  //     enable_dma_post_enforcement: true,
  //     enable_dma_web_toast: true,
  //     enable_docked_chat_messages: true,
  //     enable_dsa_one_click_ata_translators_infeed_elements: true,
  //     enable_dynamic_at_sign_for_channel_creation_handle: true,
  //     enable_entity_store_from_dependency_injection: true,
  //     enable_eom_webview_header: true,
  //     enable_exit_confirmation_dialog: true,
  //     enable_flow_logging_p4e: true,
  //     enable_gel_log_commands: true,
  //     enable_get_account_switcher_endpoint_on_webfe: true,
  //     enable_ghost_view_rendering_limited_h5_client: true,
  //     enable_google_payment_billing_command_client_support: true,
  //     enable_handle_search_on_channel_switcher: true,
  //     enable_handles_account_menu_switcher: true,
  //     enable_handles_in_mention_suggest_posts: true,
  //     enable_hlp_client_icon_pick: true,
  //     enable_identity_attributes_for_live_chat: true,
  //     enable_image_poll_post_creation: true,
  //     enable_inline_shorts_on_wn: true,
  //     enable_interstitial_entity_check: true,
  //     enable_is_extended_monitoring: true,
  //     enable_lcr_emoji_fountain: true,
  //     enable_loggingcontext_trackingparams: true,
  //     enable_masthead_quartile_ping_fix: true,
  //     enable_memberships_and_purchases: true,
  //     enable_mentions_in_reposts: true,
  //     enable_microformat_data: true,
  //     enable_mini_app_microformats: true,
  //     enable_mixed_direction_formatted_strings: true,
  //     enable_multi_image_post_creation: true,
  //     enable_names_handles_account_switcher: true,
  //     enable_native_bridge_view_saved_playables: true,
  //     enable_network_request_logging_on_game_events: true,
  //     enable_new_channel_creation_for_id4all: true,
  //     enable_offer_suppression: true,
  //     enable_on_yt_command_executor_command_to_navigate: true,
  //     enable_pacf_slot_asde_infeed_h5: true,
  //     enable_pacf_slot_asde_player_byte_h5: true,
  //     enable_pacf_slot_asde_player_byte_h5_TV: true,
  //     enable_pass_sdc_get_accounts_list: true,
  //     enable_pl_r_c: true,
  //     enable_pl_r_c_s: true,
  //     enable_pl_r_si_fa: true,
  //     enable_playable_a11y_label_with_badge_text: true,
  //     enable_playable_container_save_button: true,
  //     enable_playable_entity_save_menu_item: true,
  //     enable_playables_url_resolution: true,
  //     enable_player_param_truncation_before_navigation_on_web: true,
  //     enable_poll_choice_border_on_web: true,
  //     enable_polymer_resin: true,
  //     enable_polymer_resin_migration: true,
  //     enable_populate_att_psd_in_abe_feedback: true,
  //     enable_populate_psd_in_abe_feedback: true,
  //     enable_post_cct_links: true,
  //     enable_post_scheduling: true,
  //     enable_premium_voluntary_pause: true,
  //     enable_programmed_playlist_color_sample: true,
  //     enable_programmed_playlist_redesign: true,
  //     enable_purchase_activity_in_paid_memberships: true,
  //     enable_quiz_creation: true,
  //     enable_reel_watch_sequence: true,
  //     enable_resolve_command_on_lwe_desktop: true,
  //     enable_respect_lang_dir: true,
  //     enable_rfa_rate_limits: true,
  //     enable_scrolling_fix: true,
  //     enable_sdf_midroll_postroll_player_bytes_video_h5: true,
  //     enable_sdf_preroll_player_bytes_video_h5: true,
  //     enable_sdf_preroll_player_bytes_video_tv: true,
  //     enable_sdk_performance_network_logging: true,
  //     enable_sdk_performance_play_logging: true,
  //     enable_section_list_scroll_to_item_section_web: true,
  //     enable_seedless_shorts_url: true,
  //     enable_server_stitched_dai: true,
  //     enable_service_ajax_csn: true,
  //     enable_servlet_errors_streamz: true,
  //     enable_servlet_streamz: true,
  //     enable_sfv_audio_pivot_url: true,
  //     enable_sfv_effect_pivot_microformat: true,
  //     enable_sfv_effect_pivot_url: true,
  //     enable_shadydom_free_scoped_node_methods: true,
  //     enable_shadydom_free_scoped_query_methods: true,
  //     enable_shadydom_free_scoped_readonly_properties_batch_one: true,
  //     enable_skip_ad_guidance_prompt: true,
  //     enable_skippable_ads_for_unplugged_ad_pod: true,
  //     enable_smearing_expansion_dai: true,
  //     enable_sparkles_web_clickable_description: true,
  //     enable_squiffle_gif_handles_landing_page: true,
  //     enable_startup_lifecycle_kids: true,
  //     enable_startup_lifecycle_parent_tools: true,
  //     enable_streamline_repost_flow: true,
  //     enable_structured_description_shorts_web_mweb: true,
  //     enable_tectonic_ad_ux_for_halftime: true,
  //     enable_third_party_info: true,
  //     enable_time_out_messages: true,
  //     enable_topsoil_wta_for_halftime_live_infra: true,
  //     enable_true_inline_for_desktop_home_feed_vac: true,
  //     enable_unavailable_videos_watch_page: true,
  //     enable_unified_cancellation_for_premium: true,
  //     enable_variable_timeout_web: true,
  //     enable_watch_next_pause_autoplay_lact: true,
  //     enable_web_gpay_command_spinner: true,
  //     enable_web_ketchup_hero_animation: true,
  //     enable_web_player_player_in_bar_feature: true,
  //     enable_web_poster_hover_animation: true,
  //     enable_web_shorts_audio_pivot: true,
  //     enable_web_shorts_mention_pivot: true,
  //     enable_web_tiered_gel: true,
  //     enable_window_constrained_buy_flow_dialog: true,
  //     enable_wiz_next_lp2_msof: true,
  //     enable_yoodle: true,
  //     enable_your_playables_feed_entrypoint: true,
  //     enable_ypc_spinners: true,
  //     enable_yt_ata_iframe_authuser: true,
  //     enable_ytc_refunds_submit_form_signal_action: true,
  //     enable_ytc_self_serve_refunds: true,
  //     endpoint_handler_logging_cleanup_killswitch: true,
  //     err_on_pl_r_c: true,
  //     export_networkless_options: true,
  //     external_fullscreen: true,
  //     external_fullscreen_with_edu: true,
  //     fetch_bid_for_dclk_status: true,
  //     fill_no_history_user_in_ip: true,
  //     fill_no_history_user_in_watch_status: true,
  //     fill_single_video_with_notify_to_lasr: true,
  //     fill_view_models_on_web_vod: true,
  //     fix_alignment_search_desktop_text_image_ads_small_screens: true,
  //     fix_isd_logging: true,
  //     gcf_config_store_enabled: true,
  //     gcf_music_innertube: true,
  //     gda_enable_playlist_download: true,
  //     global_spacebar_pause: true,
  //     h5_companion_enable_adcpn_macro_substitution_for_click_pings: true,
  //     h5_enable_generic_error_logging_event: true,
  //     h5_inplayer_enable_adcpn_macro_substitution_for_click_pings: true,
  //     h5_reset_cache_and_filter_before_update_masthead: true,
  //     handles_in_mention_suggest_posts: true,
  //     hide_endpoint_overflow_on_ytd_display_ad_renderer: true,
  //     html5_enable_ads_client_monitoring_log_tv: true,
  //     html5_enable_single_video_vod_ivar_on_pacf: true,
  //     html5_log_trigger_events_with_debug_data: true,
  //     html5_recognize_predict_start_cue_point: true,
  //     html5_server_stitched_dai_group: true,
  //     il_attach_cache_limit: true,
  //     il_use_view_model_logging_context: true,
  //     imp_cache_player_requests: true,
  //     include_autoplay_count_in_playlists: true,
  //     is_part_of_any_user_engagement_experiment: true,
  //     json_condensed_response: true,
  //     kev_adb_pg: true,
  //     kevlar_app_shortcuts: true,
  //     kevlar_appbehavior_attach_startup_tasks: true,
  //     kevlar_appshell_service_worker: true,
  //     kevlar_autofocus_menu_on_keyboard_nav: true,
  //     kevlar_autonav_popup_filtering: true,
  //     kevlar_av_eliminate_polling: true,
  //     kevlar_c3po_to_wiz_1: true,
  //     kevlar_c3po_to_wiz_2: true,
  //     kevlar_cache_cold_load_response: true,
  //     kevlar_cache_on_ttl_player: true,
  //     kevlar_cache_on_ttl_search: true,
  //     kevlar_calculate_grid_collapsible: true,
  //     kevlar_cancel_scheduled_comment_jobs_on_navigate: true,
  //     kevlar_channel_creation_form_resolver: true,
  //     kevlar_channel_trailer_multi_attach: true,
  //     kevlar_chapters_list_view_seek_by_chapter: true,
  //     kevlar_clear_duplicate_pref_cookie: true,
  //     kevlar_clear_non_displayable_url_params: true,
  //     kevlar_client_enable_shorts_player_bootstrap: true,
  //     kevlar_client_side_screens: true,
  //     kevlar_command_handler: true,
  //     kevlar_command_handler_clicks: true,
  //     kevlar_command_handler_formatted_string: true,
  //     kevlar_command_url: true,
  //     kevlar_continue_playback_without_player_response: true,
  //     kevlar_decorate_endpoint_with_onesie_config: true,
  //     kevlar_delay_watch_initial_data: true,
  //     kevlar_disable_background_prefetch: true,
  //     kevlar_disable_pending_command: true,
  //     kevlar_dragdrop_fast_scroll: true,
  //     kevlar_dropdown_fix: true,
  //     kevlar_droppable_prefetchable_requests: true,
  //     kevlar_early_popup_close: true,
  //     kevlar_enable_download_upsell_type_a: true,
  //     kevlar_enable_editable_playlists: true,
  //     kevlar_enable_em_offlineable_discovery: true,
  //     kevlar_enable_keto_batch_17_9: true,
  //     kevlar_enable_reorderable_playlists: true,
  //     kevlar_enable_shorts_prefetch_in_sequence: true,
  //     kevlar_enable_shorts_response_chunking: true,
  //     kevlar_enable_up_arrow: true,
  //     kevlar_exit_fullscreen_leaving_watch: true,
  //     kevlar_fetch_pbj: true,
  //     kevlar_fill_offline_availability_type_for_gda: true,
  //     kevlar_fix_playlist_continuation: true,
  //     kevlar_flexible_menu: true,
  //     kevlar_fluid_touch_scroll: true,
  //     kevlar_frontend_queue_recover: true,
  //     kevlar_gel_error_routing: true,
  //     kevlar_guide_refresh: true,
  //     kevlar_help_use_locale: true,
  //     kevlar_hide_playlist_playback_status: true,
  //     kevlar_hide_pp_url_param: true,
  //     kevlar_hide_time_continue_url_param: true,
  //     kevlar_home_skeleton: true,
  //     kevlar_js_fixes: true,
  //     kevlar_keyboard_button_focus: true,
  //     kevlar_larger_three_dot_tap: true,
  //     kevlar_lazy_list_resume_for_autofill: true,
  //     kevlar_local_innertube_response: true,
  //     kevlar_log_updated_time_for_smart_downloads: true,
  //     kevlar_macro_markers_keyboard_shortcut: true,
  //     kevlar_mandatory_icon_data_killswitch: true,
  //     kevlar_masthead_store: true,
  //     kevlar_mealbar_above_player: true,
  //     kevlar_miniplayer: true,
  //     kevlar_miniplayer_expand_top: true,
  //     kevlar_miniplayer_play_pause_on_scrim: true,
  //     kevlar_miniplayer_queue_user_activation: true,
  //     kevlar_mix_handle_first_endpoint_different: true,
  //     kevlar_modern_sd: true,
  //     kevlar_modern_sd_v2: true,
  //     kevlar_next_cold_on_auth_change_detected: true,
  //     kevlar_nitrate_driven_tooltips: true,
  //     kevlar_no_autoscroll_on_playlist_hover: true,
  //     kevlar_op_infra: true,
  //     kevlar_op_warm_pages: true,
  //     kevlar_pandown_polyfill: true,
  //     kevlar_passive_event_listeners: true,
  //     kevlar_playback_associated_queue: true,
  //     kevlar_player_cached_load_config: true,
  //     kevlar_player_check_ad_state_on_stop: true,
  //     kevlar_player_load_player_no_op: true,
  //     kevlar_player_new_bootstrap_adoption: true,
  //     kevlar_player_playlist_use_local_index: true,
  //     kevlar_player_watch_endpoint_navigation: true,
  //     kevlar_playlist_drag_handles: true,
  //     kevlar_playlist_use_x_close_button: true,
  //     kevlar_prefetch: true,
  //     kevlar_prevent_polymer_dynamic_font_load: true,
  //     kevlar_refresh_gesture: true,
  //     kevlar_rendererstamper_event_listener: true,
  //     kevlar_replace_short_to_short_history_state: true,
  //     kevlar_request_sequencing: true,
  //     kevlar_resolve_command_for_confirm_dialog: true,
  //     kevlar_response_command_processor_page: true,
  //     kevlar_scroll_chips_on_touch: true,
  //     kevlar_scrollbar_rework: true,
  //     kevlar_service_command_check: true,
  //     kevlar_set_internal_player_size: true,
  //     kevlar_shell_for_downloads_page: true,
  //     kevlar_shorts_scroll_v2: true,
  //     kevlar_shorts_seedless_retry_initial_load: true,
  //     kevlar_should_maintain_stable_list: true,
  //     kevlar_show_em_dl_btn: true,
  //     kevlar_show_em_dl_menu_item: true,
  //     kevlar_show_em_dl_settings_tab: true,
  //     kevlar_show_playlist_dl_btn: true,
  //     kevlar_startup_lifecycle: true,
  //     kevlar_structured_description_content_inline: true,
  //     kevlar_system_icons: true,
  //     kevlar_tabs_gesture: true,
  //     kevlar_text_inline_expander_formatted_snippet: true,
  //     kevlar_three_dot_ink: true,
  //     kevlar_thumbnail_fluid: true,
  //     kevlar_toast_manager: true,
  //     kevlar_topbar_logo_fallback_home: true,
  //     kevlar_touch_feedback: true,
  //     kevlar_touch_gesture_ves: true,
  //     kevlar_transcript_engagement_panel: true,
  //     kevlar_tuner_run_default_comments_delay: true,
  //     kevlar_tuner_should_defer_detach: true,
  //     kevlar_typography_spacing_update: true,
  //     kevlar_typography_update: true,
  //     kevlar_unified_errors_init: true,
  //     kevlar_use_response_ttl_to_invalidate_cache: true,
  //     kevlar_use_vimio_behavior: true,
  //     kevlar_use_wil_icons: true,
  //     kevlar_use_ytd_player: true,
  //     kevlar_variable_youtube_sans: true,
  //     kevlar_vimio_use_shared_monitor: true,
  //     kevlar_voice_logging_fix: true,
  //     kevlar_voice_search_use_yt_endpoint: true,
  //     kevlar_watch_cinematics: true,
  //     kevlar_watch_color_update: true,
  //     kevlar_watch_comments_ep_disable_theater: true,
  //     kevlar_watch_disable_legacy_metadata_updates: true,
  //     kevlar_watch_drag_handles: true,
  //     kevlar_watch_flexy_comments_manager: true,
  //     kevlar_watch_flexy_miniplayer_manager: true,
  //     kevlar_watch_flexy_playlist_manager: true,
  //     kevlar_watch_flexy_theater_manager: true,
  //     kevlar_watch_flexy_use_controller: true,
  //     kevlar_watch_focus_on_engagement_panels: true,
  //     kevlar_watch_gesture_pandown: true,
  //     kevlar_watch_hide_comments_teaser: true,
  //     kevlar_watch_hide_comments_while_panel_open: true,
  //     kevlar_watch_js_panel_height: true,
  //     kevlar_watch_metadata_refresh: true,
  //     kevlar_watch_metadata_refresh_attached_subscribe: true,
  //     kevlar_watch_metadata_refresh_clickable_description: true,
  //     kevlar_watch_metadata_refresh_compact_view_count: true,
  //     kevlar_watch_metadata_refresh_description_info_dedicated_line: true,
  //     kevlar_watch_metadata_refresh_description_inline_expander: true,
  //     kevlar_watch_metadata_refresh_description_primary_color: true,
  //     kevlar_watch_metadata_refresh_for_live_killswitch: true,
  //     kevlar_watch_metadata_refresh_full_width_description: true,
  //     kevlar_watch_metadata_refresh_left_aligned_video_actions: true,
  //     kevlar_watch_metadata_refresh_lower_case_video_actions: true,
  //     kevlar_watch_metadata_refresh_narrower_item_wrap: true,
  //     kevlar_watch_metadata_refresh_no_old_secondary_data: true,
  //     kevlar_watch_metadata_refresh_relative_date: true,
  //     kevlar_watch_metadata_refresh_top_aligned_actions: true,
  //     kevlar_watch_modern_metapanel: true,
  //     kevlar_watch_modern_panels: true,
  //     kevlar_watch_panel_height_matches_player: true,
  //     kevlar_wiz_player_microformat: true,
  //     kevlar_woffle: true,
  //     kevlar_woffle_fallback_image: true,
  //     kevlar_woffle_log_thumbnail_failure_ve: true,
  //     kevlar_ytb_live_badges: true,
  //     killswitch_toggle_button_behavior_resolve_command: true,
  //     live_chat_channel_activity: true,
  //     live_chat_emoji_picker_toggle_state: true,
  //     live_chat_enable_command_handler_resolver_map: true,
  //     live_chat_enable_controller_extraction: true,
  //     live_chat_enable_qna_banner_overflow_menu_actions: true,
  //     live_chat_enable_rta_manager: true,
  //     live_chat_enable_send_button_in_slow_mode: true,
  //     live_chat_increased_min_height: true,
  //     live_chat_over_playlist: true,
  //     live_chat_require_space_for_autocomplete_emoji: true,
  //     live_chat_unclickable_message: true,
  //     live_chat_web_input_update: true,
  //     live_chat_web_use_emoji_manager_singleton: true,
  //     live_chat_whole_message_clickable: true,
  //     log_errors_through_nwl_on_retry: true,
  //     log_gel_compression_latency: true,
  //     log_heartbeat_with_lifecycles: true,
  //     log_vis_on_tab_change: true,
  //     log_web_endpoint_to_layer: true,
  //     main_app_sink_wrapper_batch_10: true,
  //     main_app_sink_wrapper_batch_11: true,
  //     main_app_sink_wrapper_batch_2: true,
  //     main_app_sink_wrapper_batch_3: true,
  //     main_app_sink_wrapper_batch_4: true,
  //     main_app_sink_wrapper_batch_5: true,
  //     main_app_sink_wrapper_batch_6: true,
  //     main_app_sink_wrapper_batch_7: true,
  //     main_app_sink_wrapper_batch_8: true,
  //     main_app_sink_wrapper_batch_9: true,
  //     mdx_enable_privacy_disclosure_ui: true,
  //     mdx_load_cast_api_bootstrap_script: true,
  //     migrate_events_to_ts: true,
  //     migrate_remaining_web_ad_badges_to_innertube: true,
  //     modernize_structured_description_playlist_lockups_v2: true,
  //     music_on_main_open_playlist_recommended_videos_in_miniplayer: true,
  //     mweb_actions_command_handler: true,
  //     mweb_command_handler: true,
  //     mweb_deprecate_skip_ve_logging: true,
  //     mweb_disable_set_autonav_state_in_player: true,
  //     mweb_enable_search_big_thumbs: true,
  //     mweb_logo_use_home_page_ve: true,
  //     mweb_render_crawler_description: true,
  //     mweb_stop_truncating_meta_tags: true,
  //     network_status_banner_display_none: true,
  //     networkless_gel: true,
  //     networkless_logging: true,
  //     new_csn_storage_design: true,
  //     no_iframe_for_web_stickiness: true,
  //     nwl_send_fast_on_unload: true,
  //     nwl_send_from_memory_when_online: true,
  //     offline_error_handling: true,
  //     pageid_as_header_web: true,
  //     pause_ad_video_on_desktop_engagement_panel_click: true,
  //     pdg_enable_flow_logging_for_super_chat: true,
  //     pdg_enable_flow_logging_for_super_stickers: true,
  //     player_allow_autonav_after_playlist: true,
  //     player_bootstrap_method: true,
  //     player_doubletap_to_seek: true,
  //     player_enable_playback_playlist_change: true,
  //     polymer_bad_build_labels: true,
  //     polymer_task_manager_proxied_promise: true,
  //     polymer_verifiy_app_state: true,
  //     polymer_ytdi_enable_global_injector: true,
  //     problem_walkthrough_sd: true,
  //     qoe_send_and_write: true,
  //     read_data_from_web_component_wrapper: true,
  //     record_app_crashed_web: true,
  //     reels_web_fast_scroll: true,
  //     reels_web_fast_scroll_shrink_player: true,
  //     reels_web_use_contain_for_first_frame: true,
  //     reels_web_use_pbs_first_shorts: true,
  //     register_web_smartimations_component: true,
  //     reload_without_polymer_innertube: true,
  //     remove_masthead_channel_banner_on_refresh: true,
  //     remove_yt_simple_endpoint_from_desktop_display_ad_title: true,
  //     replace_closure_window_with_updated_ytwindow_in_studio: true,
  //     rich_grid_resize_observer: true,
  //     rich_grid_resize_observer_only: true,
  //     rich_grid_watch_hide_rows_above: true,
  //     scheduler_use_raf_by_default: true,
  //     search_ui_enable_pve_buy_button: true,
  //     search_ui_official_cards_enable_paid_virtual_event_buy_button: true,
  //     searchbox_reporting: true,
  //     serve_pdp_at_canonical_url: true,
  //     service_worker_enabled: true,
  //     service_worker_push_enabled: true,
  //     service_worker_push_home_page_prompt: true,
  //     service_worker_push_watch_page_prompt: true,
  //     service_worker_subscribe_with_vapid_key: true,
  //     shared_enable_controller_extraction: true,
  //     shell_load_gcf: true,
  //     shorts_controller_retrieve_seedless_sequence: true,
  //     shorts_desktop_watch_while_p2: true,
  //     shorts_desktop_watch_while_sdp: true,
  //     shorts_in_playlists_web: true,
  //     shorts_overlay_reshuffle: true,
  //     should_clear_video_data_on_player_cued_unstarted: true,
  //     skip_invalid_ytcsi_ticks: true,
  //     skip_ls_gel_retry: true,
  //     skip_setting_info_in_csi_data_object: true,
  //     smarter_ve_dedupping: true,
  //     smartimation_background: true,
  //     sponsorships_free_creator_gifting: true,
  //     start_client_gcf: true,
  //     start_client_gcf_for_player: true,
  //     start_sending_config_hash: true,
  //     suppress_error_204_logging: true,
  //     transport_use_scheduler: true,
  //     trigger_impression_pings_on_view_search_desktop: true,
  //     update_log_event_config: true,
  //     update_ytWindow_library_use_closure_window_library: true,
  //     use_ads_engagement_panel_desktop_footer_cta: true,
  //     use_better_post_dismissals: true,
  //     use_border_and_grid_wrapping_on_desktop_panel_tiles: true,
  //     use_color_palettes_modern_collections_v2: true,
  //     use_core_sm: true,
  //     use_csi_stp_handler: true,
  //     use_event_time_ms_header: true,
  //     use_fifo_for_networkless: true,
  //     use_flow_bottom_bar_view_model_in_flow_step_renderer: true,
  //     use_infogel_early_logging: true,
  //     use_new_cml: true,
  //     use_new_in_memory_storage: true,
  //     use_new_nwl_initialization: true,
  //     use_new_nwl_stw: true,
  //     use_new_nwl_wts: true,
  //     use_not_now_dl_upsell_dismiss_cta: true,
  //     use_player_abuse_bg_library: true,
  //     use_request_time_ms_header: true,
  //     use_session_based_sampling: true,
  //     use_ts_visibilitylogger: true,
  //     use_unified_flag_accessor: true,
  //     use_watch_fragments2: true,
  //     use_ytd_player_for_desktop_masthead: true,
  //     vss_final_ping_send_and_write: true,
  //     vss_playback_use_send_and_write: true,
  //     warm_load_nav_start_web: true,
  //     warm_op_csn_cleanup: true,
  //     web_always_load_chat_support: true,
  //     web_amsterdam_playlists: true,
  //     web_amsterdam_post_mvp_playlists: true,
  //     web_animated_actions: true,
  //     web_animated_like: true,
  //     web_animated_like_lazy_load: true,
  //     web_api_url: true,
  //     web_appshell_purge_trigger: true,
  //     web_appshell_refresh_trigger: true,
  //     web_autonav_allow_off_by_default: true,
  //     web_button_rework: true,
  //     web_button_rework_with_live: true,
  //     web_chat_prevent_chat_header_overflow: true,
  //     web_cinematic_light_theme: true,
  //     web_collect_offline_state: true,
  //     web_csi_action_sampling_enabled: true,
  //     web_csi_debug_sample_enabled: true,
  //     web_darker_dark_theme: true,
  //     web_darker_dark_theme_deprecate: true,
  //     web_darker_dark_theme_live_chat: true,
  //     web_dedupe_ve_grafting: true,
  //     web_defer_shorts_ui: true,
  //     web_defer_shorts_ui_phase2: true,
  //     web_deprecate_service_ajax_map_dependency: true,
  //     web_disable_channels_chapter_entrypoint: true,
  //     web_disable_vertical_scroll_chips: true,
  //     web_early_logging_time_init: true,
  //     web_enable_ab_em_rsp: true,
  //     web_enable_ab_rsp_cl: true,
  //     web_enable_abd_ref: true,
  //     web_enable_adaptive_appl_signal: true,
  //     web_enable_dynamic_metadata: true,
  //     web_enable_dynamic_suggested_action: true,
  //     web_enable_error_204: true,
  //     web_enable_history_cache_map: true,
  //     web_enable_voz_audio_feedback: true,
  //     web_enable_youtab: true,
  //     web_engagement_panel_show_description: true,
  //     web_fill_shorts_detailed_accessibility: true,
  //     web_fill_watch_endpoint_in_verify_age: true,
  //     web_filled_subscribed_button: true,
  //     web_fix_fine_scrubbing_false_play: true,
  //     web_forward_command_on_pbj: true,
  //     web_gel_timeout_cap: true,
  //     web_guide_entry_role_is_link: true,
  //     web_guide_ui_refresh: true,
  //     web_header_eu_about_these_results: true,
  //     web_hide_autonav_keyline: true,
  //     web_horizontal_list_focus_bugfix: true,
  //     web_infocards_teaser_show_logging_fix: true,
  //     web_inline_player_enabled: true,
  //     web_kevlar_enable_adaptive_signals: true,
  //     web_localized_cc_icon: true,
  //     web_log_memory_total_kbytes: true,
  //     web_log_player_watch_next_ticks: true,
  //     web_log_reels_ticks: true,
  //     web_logging_max_batch_hard_limit: true,
  //     web_memoize_inflight_requests: true,
  //     web_modern_ads: true,
  //     web_modern_buttons: true,
  //     web_modern_buttons_bl_survey: true,
  //     web_modern_chips: true,
  //     web_modern_collections: true,
  //     web_modern_collections_v2: true,
  //     web_modern_dialogs: true,
  //     web_modern_player_settings_quality_bottom: true,
  //     web_modern_playlists: true,
  //     web_modern_subscribe: true,
  //     web_modern_tabs: true,
  //     web_modern_typography: true,
  //     web_move_autoplay_video_under_chip: true,
  //     web_one_platform_error_handling: true,
  //     web_persist_server_autonav_state_on_client: true,
  //     web_player_add_ve_conversion_logging_to_outbound_links: true,
  //     web_player_always_enable_auto_translation: true,
  //     web_player_autonav_empty_suggestions_fix: true,
  //     web_player_autonav_next_button_renderer: true,
  //     web_player_autonav_toggle_always_listen: true,
  //     web_player_autonav_use_server_provided_state: true,
  //     web_player_disable_inline_scrubbing: true,
  //     web_player_enable_cultural_moment_overlay: true,
  //     web_player_enable_early_warning_snackbar: true,
  //     web_player_enable_featured_product_banner_exclusives_on_desktop: true,
  //     web_player_enable_featured_product_banner_price_deals_on_desktop: true,
  //     web_player_enable_info_button_in_banner_on_desktop: true,
  //     web_player_enable_overflow_button_in_banner_on_desktop: true,
  //     web_player_enable_premium_hbr_in_h5_api: true,
  //     web_player_enable_premium_hbr_playback_cap: true,
  //     web_player_enable_vod_featured_product_banner_on_desktop: true,
  //     web_player_entities_middleware: true,
  //     web_player_log_click_before_generating_ve_conversion_params: true,
  //     web_player_move_autonav_toggle: true,
  //     web_player_should_honor_include_asr_setting: true,
  //     web_player_small_hbp_settings_menu: true,
  //     web_player_split_event_bus: true,
  //     web_player_topify_subtitles_for_shorts: true,
  //     web_player_touch_mode_improvements: true,
  //     web_player_use_heartbeat_poll_delay_ms: true,
  //     web_player_use_new_api_for_quality_pullback: true,
  //     web_player_ve_conversion_fixes_for_channel_info: true,
  //     web_prefetch_preload_video: true,
  //     web_progress_bar_window_mouse_events: true,
  //     web_prs_testing_mode_killswitch: true,
  //     web_remember_guide_toggle_state: true,
  //     web_rendererstamper_event_listener: true,
  //     web_replace_thumbnail_with_image: true,
  //     web_resizable_advertiser_banner_on_masthead: true,
  //     web_resizable_advertiser_banner_on_masthead_safari_fix: true,
  //     web_rich_shelf_show_less_button: true,
  //     web_rich_shelf_show_less_button_overlapping_divider: true,
  //     web_rich_shelf_show_more_button: true,
  //     web_rich_shelf_show_more_button_overlapping_divider: true,
  //     web_rounded_thumbnails: true,
  //     web_scheduler_auto_init: true,
  //     web_segmented_like_dislike_button: true,
  //     web_sheets_ui_refresh: true,
  //     web_shorts_badge_migration: true,
  //     web_shorts_deflate_inactive_slides_aggressive: true,
  //     web_shorts_shelf_on_search: true,
  //     web_shorts_skip_loading_same_index: true,
  //     web_shorts_suggested_action_no_bvm: true,
  //     web_shorts_surveys: true,
  //     web_simple_scriptloader: true,
  //     web_simple_styleloader: true,
  //     web_snackbar_ui_refresh: true,
  //     web_speedmaster_spacebar_control: true,
  //     web_structured_description_show_more: true,
  //     web_suggested_actions_backwards_compatible: true,
  //     web_suggestion_box_bolder: true,
  //     web_suggestion_box_restyle: true,
  //     web_supports_animations_api: true,
  //     web_update_flexible_buttons_after_renderidom: true,
  //     web_use_cache_for_image_fallback: true,
  //     web_use_client_imp_controls: true,
  //     web_vision_pro_detection_killswitch: true,
  //     web_watch_chips_mask_fade: true,
  //     web_watch_cinematics_preferred_reduced_motion_default_disabled: true,
  //     web_watch_log_theater_mode: true,
  //     web_watch_rounded_player_large: true,
  //     web_watch_theater_chat: true,
  //     web_watch_theater_fixed_chat: true,
  //     web_watch_typography_title_headline_xs: true,
  //     web_watch_updated_metadata_server_initial_delay: true,
  //     web_yt_config_context: true,
  //     webfe_disable_ab_em_plb: true,
  //     wil_icon_render_when_idle: true,
  //     wiz_use_generic_logging_infra: true,
  //     woffle_clean_up_after_entity_migration: true,
  //     woffle_enable_download_status: true,
  //     woffle_orchestration: true,
  //     woffle_playlist_only_show_completed: true,
  //     woffle_playlist_optimization: true,
  //     woffle_playlist_visitor_fix: true,
  //     woffle_used_state_report: true,
  //     your_data_entrypoint: true,
  //     yt_network_manager_component_to_lib_killswitch: true,
  //     ytidb_clear_embedded_player: true,
  //     ytidb_fetch_datasync_ids_for_data_cleanup: true,
  //     H5_async_logging_delay_ms: 30000,
  //     autoplay_pause_by_lact_sampling_fraction: 0,
  //     browse_ajax_log_warning_fraction: 1,
  //     cinematic_watch_effect_opacity: 0.4,
  //     dynamic_metadata_update_interaction_delay_period_sec: 5,
  //     formatted_description_log_warning_fraction: 0.01,
  //     kevlar_tuner_clamp_device_pixel_ratio: 2,
  //     kevlar_tuner_thumbnail_factor: 1,
  //     kevlar_unified_player_logging_threshold: 1,
  //     log_window_onerror_fraction: 0.1,
  //     polymer_property_access_logging_percent: 0,
  //     polymer_report_client_url_requested_rate: 0.001,
  //     polymer_report_missing_web_navigation_endpoint_rate: 0.001,
  //     prefetch_coordinator_error_logging_sampling_rate: 1,
  //     tv_pacf_logging_sample_rate: 0.01,
  //     web_shorts_error_logging_threshold: 0.001,
  //     web_shorts_intersection_observer_threshold_override: 0,
  //     web_system_health_fraction: 0.01,
  //     ytidb_transaction_ended_event_rate_limit: 0.02,
  //     ytidb_transaction_ended_event_rate_limit_session: 0.2,
  //     ytidb_transaction_ended_event_rate_limit_transaction: 0.1,
  //     active_time_update_interval_ms: 10000,
  //     autoplay_pause_by_lact_sec: 0,
  //     autoplay_time: 8000,
  //     autoplay_time_for_fullscreen: 3000,
  //     autoplay_time_for_music_content: 3000,
  //     botguard_async_snapshot_timeout_ms: 3000,
  //     check_navigator_accuracy_timeout_ms: 0,
  //     cinematic_watch_css_filter_blur_strength: 40,
  //     cinematic_watch_fade_out_duration: 500,
  //     client_streamz_web_flush_count: 100,
  //     client_streamz_web_flush_interval_seconds: 60,
  //     close_webview_delay_ms: 100,
  //     cloud_save_game_data_rate_limit_ms: 3000,
  //     compression_disable_point: 10,
  //     desktop_fountain_emoji_size_px: 20,
  //     desktop_search_suggestion_tap_target: 0,
  //     external_fullscreen_button_click_threshold: 2,
  //     external_fullscreen_button_shown_threshold: 10,
  //     gel_min_batch_size: 3,
  //     gel_queue_timeout_max_ms: 300000,
  //     get_async_timeout_ms: 60000,
  //     hide_cta_for_home_web_video_ads_animate_in_time: 2,
  //     high_priority_flyout_frequency: 3,
  //     initial_gel_batch_timeout: 2000,
  //     innertube_request_limit_ms: 3000,
  //     kevlar_lockup_hover_delay: 32,
  //     kevlar_mini_guide_width_threshold: 791,
  //     kevlar_persistent_guide_width_threshold: 1312,
  //     kevlar_time_caching_end_threshold: 15,
  //     kevlar_time_caching_start_threshold: 15,
  //     kevlar_tooltip_impression_cap: 2,
  //     kevlar_tuner_default_comments_delay: 1000,
  //     kevlar_tuner_scheduler_soft_state_timer_ms: 800,
  //     kevlar_tuner_visibility_time_between_jobs_ms: 100,
  //     kevlar_watch_flexy_metadata_height: 136,
  //     kevlar_watch_grid_below_player_value: 0,
  //     kevlar_watch_grid_sidebar_min_width: 300,
  //     kevlar_watch_max_player_width: 1280,
  //     kevlar_watch_metadata_refresh_description_lines: 3,
  //     kevlar_watch_page_columns_top_padding: 24,
  //     kevlar_watch_page_horizontal_margin: 24,
  //     kevlar_watch_page_margin: 24,
  //     kevlar_watch_player_min_height: 360,
  //     kevlar_watch_secondary_width: 402,
  //     kevlar_watch_two_column_width_threshold: 1000,
  //     live_chat_chunk_rendering: 0,
  //     live_chat_emoji_picker_restyle_bottom_px: 0,
  //     live_chat_emoji_picker_restyle_height_percent: 0,
  //     live_chat_emoji_picker_restyle_height_px: 0,
  //     live_chat_emoji_picker_restyle_width_px: 0,
  //     live_chat_max_chunk_size: 5,
  //     live_chat_min_chunk_interval_ms: 300,
  //     live_reactions_desktop_fab_relocation_mode: 0,
  //     max_body_size_to_compress: 500000,
  //     max_duration_to_consider_mouseover_as_hover: 600000,
  //     max_prefetch_window_sec_for_livestream_optimization: 10,
  //     min_mouse_still_duration: 100,
  //     min_prefetch_offset_sec_for_livestream_optimization: 20,
  //     minimum_duration_to_consider_mouseover_as_hover: 500,
  //     mweb_history_manager_cache_size: 100,
  //     mweb_history_manager_w2w_ttl: 0,
  //     network_polling_interval: 30000,
  //     pbj_navigate_limit: -1,
  //     play_click_interval_ms: 30000,
  //     play_ping_interval_ms: 10000,
  //     post_type_icons_rearrange: 1,
  //     prefetch_comments_ms_after_video: 0,
  //     prefetch_coordinator_command_timeout_ms: 60000,
  //     prefetch_coordinator_max_inflight_requests: 1,
  //     rich_grid_max_item_width: 500,
  //     rich_grid_min_item_width: 310,
  //     send_config_hash_timer: 0,
  //     service_worker_push_logged_out_prompt_watches: -1,
  //     service_worker_push_prompt_cap: -1,
  //     service_worker_push_prompt_delay_microseconds: 3888000000000,
  //     slow_compressions_before_abandon_count: 4,
  //     swatcheroo_rich_grid_delay: 0,
  //     user_engagement_experiments_rate_limit_ms: 86400000,
  //     user_mention_suggestions_edu_impression_cap: 10,
  //     visibility_time_between_jobs_ms: 100,
  //     web_cold_open_animation_initial_delay: 2000,
  //     web_emulated_idle_callback_delay: 0,
  //     web_foreground_heartbeat_interval_ms: 28000,
  //     web_gel_debounce_ms: 60000,
  //     web_logging_max_batch: 150,
  //     web_player_caption_language_preference_stickiness_duration: 30,
  //     web_search_inline_player_triggering_delay: 0,
  //     web_shorts_deflate_inactive_slides_aggressive_distance: 2,
  //     web_shorts_inline_playback_preview_ms: 5000,
  //     web_smoothness_test_duration_ms: 0,
  //     web_smoothness_test_method: 0,
  //     wil_icon_max_concurrent_fetches: 9999,
  //     wn_grid_max_item_width: 0,
  //     wn_grid_min_item_width: 0,
  //     yoodle_end_time_utc: 0,
  //     yoodle_start_time_utc: 0,
  //     ytidb_remake_db_retries: 3,
  //     ytidb_reopen_db_retries: 3,
  //     WebClientReleaseProcessCritical__youtube_web_client_version_override: "",
  //     asset_caching_http_max_age: "",
  //     comment_input_box_triggering_strategy: "NEVER",
  //     debug_forced_internalcountrycode: "",
  //     desktop_search_bigger_thumbs_style: "BIG",
  //     desktop_searchbar_style: "default",
  //     embeds_web_synth_ch_headers_banned_urls_regex: "",
  //     il_payload_scraping: "",
  //     kevlar_duplicate_pref_cookie_domain_override: "",
  //     kevlar_link_capturing_mode: "",
  //     live_chat_unicode_emoji_json_url:
  //       "https://www.gstatic.com/youtube/img/emojis/emojis-svg-9.json",
  //     polymer_task_manager_status: "production",
  //     reels_action_justified_content: "flex-start",
  //     reels_metadata_justified_content: "flex-start",
  //     reels_navigation_justify_content: "space-between",
  //     search_overview_link_style: "green_track",
  //     service_worker_push_force_notification_prompt_tag: "1",
  //     service_worker_scope: "/",
  //     web_client_version_override: "",
  //     web_home_feed_reload_experience: "none",
  //     web_modern_subscribe_style: "filled",
  //     web_shorts_expanded_overlay_type: "DEFAULT",
  //     web_shorts_overlay_vertical_orientation: "bottom",
  //     yoodle_base_url: "",
  //     yoodle_webp_base_url: "",
  //     conditional_lab_ids: [],
  //     guide_business_info_countries: ["KR"],
  //     guide_legal_footer_enabled_countries: ["NL", "ES"],
  //     html5_profiler_trace_enums: [],
  //     kevlar_command_handler_command_banlist: [],
  //     kevlar_page_service_url_prefix_carveouts: [],
  //     web_op_signal_type_banlist: [],
  //   };

  //   const resilienceOptimizations = {
  //     // Core network resilience
  //     network_polling_interval: 15000, // Reduced from 30000 for faster recovery
  //     enable_variable_timeout_web: true,
  //     innertube_request_limit_ms: 5000, // Increased from 3000 for more retry time

  //     // Player bootstrap and recovery
  //     player_bootstrap_method: true,
  //     kevlar_continue_playback_without_player_response: true,
  //     enable_frontend_queue_recover: true,
  //     enable_player_entities_middleware: true,

  //     // Enhanced error handling
  //     log_errors_through_nwl_on_retry: true,
  //     enable_servlet_streamz: true,
  //     enable_servlet_errors_streamz: true,

  //     // Connection monitoring
  //     web_foreground_heartbeat_interval_ms: 14000, // Reduced from 28000 for faster detection
  //     enable_is_extended_monitoring: true,

  //     // Player state management
  //     kevlar_player_check_ad_state_on_stop: true,
  //     kevlar_player_new_bootstrap_adoption: true,

  //     // Request handling optimizations
  //     gel_queue_timeout_max_ms: 60000, // Increased from default for longer retry windows
  //     get_async_timeout_ms: 90000, // Increased for longer async operations

  //     // Additional resilience features
  //     enable_active_view_display_ad_renderer_web_home: true,
  //     enable_async_ab_enf: true,
  //     enable_client_streamz_web: true,
  //     enable_service_ajax_csn: true,

  //     // Recovery mechanisms
  //     kevlar_frontend_queue_recover: true,
  //     web_player_move_autonav_toggle: true,
  //     web_player_vimio_use_shared_monitor: true,

  //     // Enhanced playback stability
  //     html5_recognize_predict_start_cue_point: true,
  //     html5_report_supports_vp9_encoding: true,
  //     html5_server_stitched_dai_group: true,

  //     // State persistence
  //     enable_persistent_device_token: true,
  //     enable_client_sli_logging: true,

  //     // Performance optimizations
  //     compress_gel: true,
  //     defer_overlays: true,
  //     defer_rendering_outside_visible_area: true,

  //     // Buffer management
  //     max_prefetch_window_sec_for_livestream_optimization: 20, // Doubled from 10
  //     min_prefetch_offset_sec_for_livestream_optimization: 30, // Increased from 20

  //     // Retry logic
  //     ytidb_remake_db_retries: 3, // Increased from 1
  //     ytidb_reopen_db_retries: 2, // Increased from 0
  //     slow_compressions_before_abandon_count: 8, // Doubled from 4

  //     // Network handling
  //     networkless_logging: true,
  //     nwl_send_fast_on_unload: true,
  //     use_new_in_memory_storage: true,
  //     use_session_based_sampling: true,
  //   };
  //   // Preserve existing config while updating specific flags
  //   const updatedFlags = {
  //     ...currentConfig.EXPERIMENT_FLAGS,
  //     ...saneConfigs,
  //     ...resilienceOptimizations,
  //     // network_polling_interval: 15000,
  //     // html5_delayed_retry_count: 3,
  //     // html5_delayed_retry_delay_ms: 2000,
  //     // live_chunk_readahead: 5,
  //     // // Additional reliability settings you might want to modify
  //     // html5_live_abr_head_miss_fraction: 0.0,
  //     // html5_streaming_xhr_time_based_consolidation_ms: 1000,
  //     // html5_max_headm_for_streaming_xhr: 0,
  //     // html5_min_readbehind_secs: 3,
  //     // html5_min_startup_buffered_media_duration_for_live_secs: 0.5,
  //     // html5_subsegment_readahead_target_buffer_health_secs: 1.0,
  //     // html5_subsegment_readahead_timeout_secs: 3.0,
  //   };
  //   console.log(JSON.stringify(currentConfig, null, 2));

  //   // @ts-expect-error "ytcfg" is a YT global
  //   window.ytcfg.set({
  //     ...currentConfig,
  //     EXPERIMENT_FLAGS: updatedFlags,
  //   });

  //   // @ts-expect-error "ytcfg" is a YT global
  //   console.log(JSON.stringify(window.ytcfg.d(), null, 2));
  // }

  // // Inject the script
  // injectScript(modifyYouTubeConfig);
}
window.addEventListener("message", async (event) => {
  if (validOrigin(event.origin)) {
    if (event.data?.event === "likeVideo") {
      if (!(await Options.get("remoteYoutubeLikeButton"))) return;
      console.log("[Holodex+] Liking the video");
      const res = await like();

      // Show an indicator based on the response
      const indicator = document.createElement("div");
      indicator.style.position = "fixed";
      indicator.style.bottom = "20px";
      indicator.style.right = "20px";
      indicator.style.padding = "10px 20px";
      indicator.style.borderRadius = "5px";
      indicator.style.color = "white";
      indicator.style.fontSize = "14px";
      indicator.style.zIndex = "9999";
      indicator.style.boxShadow = "0 2px 6px rgba(0,0,0,0.3)";
      indicator.style.transition = "opacity 0.3s ease-in-out";
      indicator.style.opacity = "1";

      if (res) {
        indicator.style.backgroundColor = "#4CAF50"; // Green for success
        indicator.innerText = "Video liked!";
      } else {
        indicator.style.backgroundColor = "#F44336"; // Red for failure
        indicator.innerText = "Failed to like the video.";
      }

      document.body.appendChild(indicator);

      // Remove the indicator after 3 seconds
      setTimeout(() => {
        indicator.style.opacity = "0";
        setTimeout(() => indicator.remove(), 300); // Wait for fade-out transition
      }, 3000);
    }
  }
});

async function getYtLikeData() {
  const doc = await fetch(`https://www.youtube.com/watch?v=${videoId}`).then(
    (r) => r.text()
  );
  const apiKey = doc.match(/"INNERTUBE_API_KEY":"(.*?)"/)?.[1];
  const context = JSON.parse(
    (doc.match(/\(\{"INNERTUBE_CONTEXT":([\w\W]*?)\}\)/) ||
      doc.match(/"INNERTUBE_CONTEXT":([\w\W]*?\}),"INNERTUBE/))?.[1] ?? "{}"
  );
  const ytClientName = doc.match(/"INNERTUBE_CONTEXT_CLIENT_NAME":(\d+),/)?.[1];
  const ytClientVersion = doc.match(
    /"INNERTUBE_CONTEXT_CLIENT_VERSION":"(.*?)"/
  )?.[1];
  const pageId = doc.match(/"DELEGATED_SESSION_ID":"(.*?)"/)?.[1];
  const likeParams = doc.match(/"likeParams":"(.*?)"/)?.[1];
  const removeLikeParams = doc.match(/"removeLikeParams":"(.*?)"/)?.[1];
  const PAPISID = document.cookie.match(/3PAPISID=([^;]*);?.*$/)?.[1];
  if (
    !apiKey ||
    Object.keys(context).length === 0 ||
    !ytClientName ||
    !ytClientVersion ||
    // !pageId ||
    !likeParams ||
    !PAPISID
  ) {
    return null;
  }
  return {
    apiKey,
    context,
    ytClientName,
    ytClientVersion,
    pageId,
    likeParams,
    removeLikeParams,
    PAPISID,
  };
}

async function like() {
  const ytLikeData = await getYtLikeData();
  if (!ytLikeData) return false;
  const {
    apiKey,
    context,
    pageId,
    ytClientName,
    ytClientVersion,
    PAPISID,
    likeParams,
  } = ytLikeData;
  const nowTime = Math.floor(Date.now() / 1000);
  try {
    const res = await fetch(
      `https://www.youtube.com/youtubei/v1/like/like?key=${apiKey}`,
      {
        method: "POST",
        referrer: `https://youtube.com/watch?v=${videoId}`,
        mode: "same-origin",
        referrerPolicy: "origin-when-cross-origin",
        headers: {
          "Content-Type": "application/json",
          "X-Goog-AuthUser": "0",
          "X-Goog-Visitor-Id": context.client.visitorData,
          ...(pageId && { "X-Goog-PageId": pageId }),
          "X-Youtube-Client-Name": ytClientName,
          "X-Youtube-Client-Version": ytClientVersion,
          "X-Origin": "https://www.youtube.com",
          "SEC-CH-UA-ARCH": "x86",
          "sec-ch-ua-platform-version": "10.0.0",
          "sec-ch-ua-full-version": "93.0.4577.82",
          Authorization: `SAPISIDHASH ${nowTime}_${await sha1(
            `${nowTime} ${PAPISID} https://www.youtube.com`
          )}`,
        },
        body: JSON.stringify({
          context,
          target: { videoId },
          params: likeParams,
        }),
      }
    ).then(async (r) => ({ status: r.status, body: await r.text() }));
    if (res.status === 200) {
      return true;
    }
  } catch (e) {
    console.error("[Holodex+] Error while sending like:", e);
  }
  return false;
}
